Markytics/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('', include('incident.urls', namespace="incident")),
    path('', include('person.urls', namespace="person")),
    path('admin/', admin.site.urls),
]

incident/urls.py
from django.urls import path
from . import views

app_name = 'incident'

urlpatterns = [
    path("incident-form/", views.create_incident, name='create-inci'),

    ]

person/urls.py
from django.urls import path
from . import views

app_name = 'person'

urlpatterns = [
    path('', views.home , name='home'),
    path("login/", views.login_request, name='login'),
    path('register/', views.register, name='register'),
    path("logout/", views.logout_request, name='logout'),

]

incident/models.py
from django.db import models
from person.models import person
from enum import Enum
import datetime

class severity(Enum):
    Mild = "Mild"
    Moderate = "Moderate"
    Severe = "Severe"
    Fatal = "Fatal"


class location(Enum):
    CH = "Corporate Headoffice"
    OPD = "Operations Department"
    WS = "Work Station"
    MD = "Marketing Division"


class incident(models.Model):
    location1 = models.CharField(max_length=10, choices=[(tag.name, tag.value) for tag in location],
                                   default=location.CH)
    location2 = models.TextField(default="abcd")
    description = models.TextField(default="abcd")
    date = models.DateField(default=datetime.date.today)
    time = models.TimeField(default=datetime.time)
    severity = models.CharField(max_length=10, choices=[(tag.name, tag.value) for tag in severity],
                                   default=severity.Mild)
    cause = models.TextField(default="abcd")
    actions  = models.TextField(default="abcd")
    type_env = models.BooleanField(default=False)
    type_inju = models.BooleanField(default=False)
    type_property = models.BooleanField(default=False)
    type_vehicle = models.BooleanField(default=False)
    reported_by = models.ForeignKey(person, on_delete=None)
    submitted = models.BooleanField(default=False)

    def __str__(self):
        return self.location2

person/models.py
from django.db import models
from django.contrib.auth.models import User
from enum import Enum
import datetime

class severity(Enum):
    Mild = "Mild"
    Moderate = "Moderate"
    Severe = "Severe"
    Fatal = "Fatal"

class location(Enum):
    CorpHead = "Corporate Headoffice"
    OPD = "Operations Department"
    WS = "Work Station"
    MD = "Marketing Division"

class person(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    admin = models.BooleanField(default=False)

incident/forms.py
from .models import incident
from django import forms

class IncidentForm(forms.ModelForm):
    class Meta:
        model = incident
        fields = ("location1", "location2", "description" , "severity" , "cause" , "date", "time", "actions" ,
                  "type_env" , "type_inju" , "type_property" , "type_vehicle" )

person/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "password1", "password2" , )

incident/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.http import HttpResponse
from .forms import IncidentForm
from django.contrib import messages
from django.contrib.auth import authenticate,login ,logout
from django.contrib.auth.forms import AuthenticationForm
from .models import incident
from person.models import person


def create_incident(request):
    if request.method == "POST":
        form = IncidentForm(request.POST)
        if form.is_valid():
            inci = form.save(False)
            inci.reported_by = person.objects.get(user=request.user)
            form.save(True)
            return redirect('person:home')
        else:
            return HttpResponse("Wrong Response.")
    else:
        form = IncidentForm()
        context = {"form": form, }
        return render(request, 'incident/incident_form.html', context)

person/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.http import HttpResponse
from .forms import UserForm
from django.contrib import messages
from django.contrib.auth import authenticate,login ,logout
from django.contrib.auth.forms import AuthenticationForm
from .models import person, User


def home(request):
    return render(request, 'index.html')


def register(request):
    form1 = UserForm()
    if request.method == 'POST':
        form1 = UserForm(request.POST)
        if form1.is_valid() :
            uss = form1.save()
            prsn= person(user=uss)
            prsn.save()
            login(request, uss)
            return redirect("person:home")
        message = 'ERROR !! Could not register. Please try again. '
        print("Error")
        context = {'message': message , 'form1': form1}
        return render(request,  'registration/registration_form2.html', context)
    return render(request, 'registration/registration_form2.html', {'form1': form1 })



def login_request(request):
    message = ''
    if request.method == 'POST':
        form = AuthenticationForm(request=request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                message = "Success: You are now logged in."
                  #as {{request.user.username}}."
                return render(request, 'index.html',{"message": message,})
            else:
                message = "Error: Invalid username or password."
        else:
            message = "Error: Invalid username or password."
    form = AuthenticationForm()
    context = {"form": form,
               "message": message, }
    return render(  request = request, template_name = "registration/login.html", context=context)


def logout_request(request):
    logout(request)
    messages.info(request, "Logged out successfully!")
    return redirect("person:home")

incident/templates/incident/incident_form.html
{% extends 'index.html' %}


{% block title %} Create Group {% endblock %}


{% block head %}
    <style>
    #id_objective , #id_syllabus , #id_text_books, #id_ref_material, #id_prerequisite
    {
          display: block;
          width: 100%;
          line-height: 40px;
          border: none;
          background: #f9f9ff;
          padding: 0 20px;
          height: 100px;
          resize: none;
          outline-color: #d0e4d0;
          outline-style: solid;
          outline-width: 1px;
            }
</style>
{% endblock %}

{% block body %}

            <div class="card">
                 <div class="card-body">
                     <h3 class="page-title text-truncate text-dark font-weight-medium mb-1">New Master Incident </h3>
                      <h4 class="page-title text-truncate text-dark font-weight-medium mb-1"> Initial Reporting </h4>

<br>
    <form action="" method="post">
    {% csrf_token %}


                                    <div class="form-body">
                                        <div class="form-group">
                                            <div class="row">
                                                <label class="col-lg-2">Location</label>
                                                <div class="col-lg-10">
                                                    <div class="row">
                                                        <div class="col-md-5">
                                                            {{ form.location1 }}
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="form-body">
                                        <div class="form-group">
                                            <div class="row">
                                                <label class="col-lg-2"> Incident Description:</label>
                                                <div class="col-lg-10">
                                                    <div class="row">
                                                        <div class="col-md-5">

                                                            <textarea name="description" class="form-control" rows="3"></textarea>

                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="form-body">
                                        <div class="form-group">
                                            <div class="row">
                                                <label class="col-lg-2">Date and Time of Incident:</label>
                                                <div class="col-lg-10">
                                                    <div class="row">
                                                        <div class="col-md-3">
                                                            <input type="date" class="form-control" id="birthday" name="date">
                                                            <input type="time" class="form-control" id="birthtime" name="time">
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>


                                    <div class="form-body">
                                        <div class="form-group">
                                            <div class="row">
                                                <label class="col-lg-2">Incident Location</label>
                                                <div class="col-lg-10">
                                                    <div class="row">
                                                        <div class="col-md-5">
                                                             <textarea name="location2" class="form-control" rows="3"></textarea>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>



                                    <div class="form-body">
                                        <div class="form-group">
                                            <div class="row">
                                                <label class="col-lg-2">Initial Severity:</label>
                                                <div class="col-lg-10">
                                                    <div class="row">
                                                        <div class="col-md-5">
                                                           <div class="form-control">
                                                            {{ form.severity }}
                                                           </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="form-body">
                                        <div class="form-group">
                                            <div class="row">
                                                <label class="col-lg-2">Suspected Cause: </label>
                                                <div class="col-lg-10">
                                                    <div class="row">
                                                        <div class="col-md-5">
                                                             <textarea name="cause" class="form-control" rows="3"></textarea>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>


                                    <div class="form-body">
                                        <div class="form-group">
                                            <div class="row">
                                                <label class="col-lg-2">Immediate Actions Taken: </label>
                                                <div class="col-lg-10">
                                                    <div class="row">
                                                        <div class="col-md-5">
                                                             <textarea name="actions" class="form-control" rows="3"></textarea>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="form-body">
                                        <div class="form-group">
                                            <div class="row">
                                                <label class="col-lg-2">Sub Incident Types:</label>
                                                <div class="col-lg-10">
                                                    <div class="row">
                                                        <div class="col-md-5">
                                                   <div class="form-check form-check-inline">
                                                   <input class="form-check-input" name="type_env" type="checkbox" id="inlineCheckbox1">
                                                   <label class="form-check-label" for="inlineCheckbox1">Environmental Incident</label>
                                                   </div>
                                                   <br>
                                                   <div class="form-check form-check-inline">
                                                   <input class="form-check-input" name="type_inju" type="checkbox" id="inlineCheckbox2" >
                                                   <label class="form-check-label" for="inlineCheckbox2">Injury/Illness</label>
                                                   </div>
                                                   <br>
                                                   <div class="form-check form-check-inline">
                                                   <input class="form-check-input" name="type_property" type="checkbox" id="inlineCheckbox3" >
                                                   <label class="form-check-label" for="inlineCheckbox3">Property Damage</label>
                                                   </div>
                                                   <br>
                                                   <div class="form-check form-check-inline">
                                                   <input class="form-check-input" name="type_vehicle" type="checkbox" id="inlineCheckbox4" >
                                                   <label class="form-check-label" for="inlineCheckbox4">Vehicle</label>
                                                   </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="form-body">
                                        <div class="form-group">
                                            <div class="row">
                                                <label class="col-lg-2"> Reported By: </label>
                                                <div class="col-lg-10">
                                                    <div class="row">
                                                        <div class="col-md-5">
                                                             {{ request.user.username }}
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>


                                    <div class="form-actions">
                                        <div class="text-right">
                                            <button type="submit" class="btn btn-info">Submit</button>
                                            <button type="submit" class="btn btn-info">Save for later</button>
                                            <button type="reset" class="btn btn-dark">Cancel</button>
                                        </div>
                                    </div>
               </form>
            </div>
            </div>


{% endblock %}

incident/templates/incident/verify_otp.html
{% extends 'base.html' %}
{% block title %} My Groups {% endblock %}
{% block body %}

       <div class="container" style="margin-top: 30px ; margin-left: 60px;">
           Just one last step . :)
           <br> <br>
        <form action="{% url 'Profile:verify-otp' %}"  method="post" enctype="multipart/form-data">
            {% csrf_token %}
        OTP- <input type="number" name="otp" placeholder="Enter OTP here." required>
            <button type="submit"> <strong> Verify </strong> </button>
        </form>
       </div>

{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" type="text/css" href="{% static "styles/bootstrap.min.css" %}">
  <link rel="stylesheet" type="text/css" href="{% static "styles/mystyle.css" %}">

</head>

{% block head %}
  <title>Home Page</title>
{% endblock %}


<body>
<nav class="navbar navbar-expand-sm fixed-top sty-navbar">
<div class="container">
    <a class="navbar-brand"> Markytics </a>
    <ul class="nav navbar-nav mr-auto">
        <li class="nav-item"><a class="nav-link" href="{% url 'person:home'%}"> Home </a></li>
        <li class="nav-item"><a class="nav-link" href="#"> About Us </a></li>
        <li class="nav-item"><a class="nav-link" href="#"> Contact </a> </li>

        {% if request.user.is_authenticated %}
        <li class="nav-item"><a class="nav-link" href="#" >  Hello {{ user.get_username }}  </a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'person:logout'%}"> Logout </a></li>
        {% else %}

        <li class="nav-item"><a class="nav-link" href="{% url 'person:login'%}">Login/Register</a></li>
        {% endif %}


    </ul>
</div>
</nav>
</body>

{% block body %}
<h1>This is the base template. :)</h1>
{% endblock %}


</html>

templates/home/about_department.html
{% extends 'base.html' %}

{% block body %}

    <div class="container section-gap" style="padding-top: 15% ">
					<h3 class="text-heading">About CSE DEPARTMENT</h3>
         <hr>
					<p class="sample-text" style="font-size: 16px;">

                        <b>The Department of Computer Science and Engineering (CSE)</b> is one of the best departments at <b>Mugneeram Bangur Memorial College of Engineering</b>. It administers bachelor's programs in Computer Science Engineering and in IT Engineering, as well as master's and PHD's programs in Computer Science and Engineering.

<br>Many full-time faculty members provide a comprehensive program that emphasizes algorithms and theory, advanced computer architecture, computer vision and pattern recognition, data mining and machine learning, distributed systems and grid computing, operating systems and computer networks, computer security, and scientific computing.

<br>The CSE department's many strengths include its high faculty-to-student ratio, state of the art facilities, renowned faculty, strong focus on undergraduate education balanced with leading-edge research, and emphasis on leadership, service, and ethics.

                        Faculty and students often collaborate on projects, working side-by-side with researchers from other colleges and departments across the campus, such as the <u>Defense Research and Development Organization (DRDO), IIT Jodhpur</u>. In addition to the excellent faculty and quality research opportunities available through the department, there is a real sense of community and teamwork here.

<br>The CSE department also provide students interested in research and projects with a recommended sequence of elective courses and guidance.

<br>These concentrations provide students to grow their strength and capabilities to cop with the changing scenario. Completion of one of the Concentrations is recorded on the student's official transcript at graduation.

<br>Graduates from the CSE department are heavily recruited by many top companies. Graduates take up careers in the computing industry, the finance industry, traditional large engineering companies, startup companies, management consulting companies, medical informatics companies, and government. Some of our top undergraduates each year enter the PhD program in Computer Science and Engineering at leading universities around the country.
					</p><hr>
    </div>
{% endblock %}

templates/home/homepage.html
{% extends 'base.html' %}
    {% block head %}

        <title>Home</title>

        <style>

            #cardHod {
                box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
                transition: 0.3s;
                width: 100%;
            }

            #cardHod:hover {
                box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
            }


            /* Add some padding inside the card container */
            .hod {
                padding: 2px 16px;
            }

        #tags {
            top: -41px;
            height: 3px;
            background-color: #bba6a6;
        }
        </style>


     {% endblock %}


    {% block body %}

          {% if message %}
                <div class="messages" style="color: green; margin-left: 60px;">
                    {{ message }}
                </div>
           {% endif %}
     {% if request.user.is_authenticated %}

     <div class="container" style="padding: 30px">
      Hello Every one! <br>
      You can report incidents here or save them for later.
         <br>
      <a href="{% url 'incident:create-inci'%}" target="blank">
          <strong> Click here to report a new incident. </strong>
      </a>
      <br>
      <a href="#" target="blank">
          <strong> View my saved incidents. </strong>
      </a>
     </div>

     {% else %}

         <div class="container" style="padding: 30px">

             <div class="messages" style="color:blue; margin-left: 60px;">
                 You need to log in first. :)
             </div>
      <br> <br>
      Hello Every one! <br>
      You can report incidents here or save them for later.
          <br>
      <a href="{% url 'incident:create-inci'%}" target="blank">
          <strong>  Click here to report a new incident.  </strong>
      </a>
      <br> <br>
      Once you have made a group-<br>
      <a href="#" target="blank">
          <strong> View my saved incidents. </strong>
      </a>
     </div>
      {% endif %}
    {% endblock %}